# Generated by Django 4.1.1 on 2022-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('permission', models.CharField(choices=[('0', 'no'), ('1', 'yes'), ('2', 'maybe')], default='0', max_length=1)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tag', models.CharField(choices=[('BU', 'Bug'), ('AM', 'Improvement'), ('TA', 'Task')], default='BU', max_length=3)),
                ('priority', models.CharField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], default='1', max_length=2)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('wip', 'In progress'), ('done', 'Completed')], default='todo', max_length=25)),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('back', 'back-end'), ('front', 'front-end'), ('iOS', 'iOS'), ('Androïd', 'Androïd')], default='back', max_length=10)),
            ],
            options={
                'ordering': ['created_time'],
                'abstract': False,
            },
        ),
    ]
