# Generated by Django 4.1.1 on 2022-10-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_issue_assignee_issue_author_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
